'use strict';
// Every action is saved. These games have no countdown or loss of earned progress.
const adjacent=(a,b,w=8)=>Math.abs(a-b)===w||(Math.floor(a/w)===Math.floor(b/w)&&Math.abs(a-b)===1);
const PIPE_LEVELS=[
 {path:[0,1,5,6,10,11,15],start:0,end:15},
 {path:[0,4,5,9,10,14,15],start:0,end:15},
 {path:[0,1,2,6,5,9,10,11,15],start:0,end:15}
];
function pipePorts(path,i){const p=path.indexOf(i);if(p<0)return [0,2];const dir=(a,b)=>b-a===1?1:b-a===-1?3:b-a===4?2:0;return [p===0?3:dir(i,path[p-1]),p===path.length-1?1:dir(i,path[p+1])];}
function waterPath(level,turns){let cell=level.start,from=3;const seen=new Set(),wet=[];while(!seen.has(cell)){seen.add(cell);const ports=pipePorts(level.path,cell).map(d=>(d+(turns[cell]||0))%4);if(!ports.includes(from))break;wet.push(cell);const out=ports.find(d=>d!==from);if(cell===level.end&&out===1)return {done:true,wet};const n=cell+[-4,1,4,-1][out];if(n<0||n>=16||!adjacent(cell,n,4))break;cell=n;from=(out+2)%4;}return {done:false,wet};}
function mini(){document.onkeydown=null;const q=current(),r=entry(),second=r.phase===5,m=second?r.second:r.mini;m.round??=0;m.message??='';const finishRound=()=>{m.round++;m.message='⭐ 작은 목표 달성! 다음 도전으로!';chime();};const draw=(title,body,hint,total=3)=>{m.done=m.round>=total;frame(title,`<div class="mission-strip"><b>${m.done?'⭐ 모두 완료!':`라운드 ${m.round+1} / ${total}`}</b><span>${hint}</span><span class="round-stars">${Array.from({length:total},(_,i)=>i<m.round?'★':'☆').join(' ')}</span></div>${m.done?`<div class="mini-cleared">${art(q.id==='sea'?6:q.id==='bus'?7:q.id==='house'?8:0)}<h3>멋지게 도왔어요!</h3><p>현장에서 찾은 이야기를 함께 살펴봐요.</p></div>`:body}${miniMessage(m)}`,miniNext(m,second));if($('next'))$('next').onclick=()=>{if(m.done)move(second?6:2);};};const again=(message)=>{m.message=message;save();mini();};
 if(q.id==='sea'&&second){
 m.caught??=[];const items=['🧴','🛍️','🐟','🥫','🪢','🍃','📦','🧴'];const rubbish=[0,1,3,4,6,7];
 const body='<div class="river-stage scene-bg '+(m.paused?'paused':'')+'"><span class="river-caption">하천 → 바다</span>'+items.map((icon,i)=>button(icon,'data-catch="'+i+'" aria-label="'+(rubbish.includes(i)?'쓰레기 잡기':'자연물 그대로 두기')+'" style="--lane:'+i%3+';--speed:'+(5+i%3)+'s;--delay:-'+(i*.65)+'s;--still-x:'+(10+i%3*30)+'%;--still-y:'+(15+Math.floor(i/3)*28)+'%" '+(m.caught.includes(i)?'disabled':''),'river-object '+(m.caught.includes(i)?'collected':''))).join('')+'</div><p class="counter">🕸️ 쓰레기 '+m.caught.length+' / 6 포착 · 물고기와 해초는 통과!</p>'+button(m.paused?'▶ 움직임 계속':'⏸ 움직임 멈추기','id="pauseRiver"','quiet');
 draw('하천 지킴이, 쓰레기를 잡아라!',body,'흘러가는 쓰레기를 눌러 잡아요. 물고기는 그대로!');if($('pauseRiver'))$('pauseRiver').onclick=()=>{m.paused=!m.paused;again(m.paused?'천천히 살펴봐도 괜찮아!':'다시 흘러간다!');};bind('[data-catch]',el=>{const i=+el.dataset.catch;if(!rubbish.includes(i))return again('물고기와 해초는 바다로 보내 줘요.');m.caught.push(i);if(m.caught.length===6){finishRound();m.caught=[];}again('🕸️ 잡았다! 바다에 가기 전에 막았어!');});
 }
 else if(q.id==='sea'){
  m.sorted??=[];m.held??=null;const icons=['🧴','🛍️','📦','🪢','🥫','🧴'];const names=['병','비닐','상자','버려진 줄','캔','병'];const bins=[0,1,0,1,0,0],order=[0,2,4,1,3,5].map((n,i)=>(n+m.round*2)%6);
  const body=`<div class="cleanup-stage scene-bg"><span class="nature n1">🐚</span><span class="nature n2">🦀</span><span class="nature n3">🍃</span>${order.map((i,k)=>button(`<span>${icons[i]}</span><small>${names[i]}</small>`,`data-trash="${i}" style="left:${10+(k%3)*31}%;top:${14+Math.floor(k/3)*44}%" ${m.sorted.includes(i)?'disabled':''}`,'floating-trash '+(m.held===i?'selected':'')+(m.sorted.includes(i)?' collected':''))).join('')}</div><div class="bin-row">${button('♻️ 병 · 캔 · 종이',`data-bin="0" ${m.held===null?'disabled':''}`)}${button('🧺 비닐 · 버려진 줄',`data-bin="1" ${m.held===null?'disabled':''}`)}<b>${m.sorted.length} / 6</b></div>`;
  draw(second?'하천에서 내려오는 쓰레기를 막자!':'해변 청소 대작전',body,'쓰레기를 집고 → 알맞은 바구니에 쏙!');
  bind('[data-trash]',el=>{m.held=+el.dataset.trash;again(`${icons[m.held]} 어디에 담을까?`);});bind('[data-bin]',el=>{if(m.held===null)return;if(+el.dataset.bin!==bins[m.held])return again('바구니에 적힌 그림과 같은 것을 찾아봐요.');m.sorted.push(m.held);m.held=null;if(m.sorted.length===6){finishRound();m.sorted=[];}again('쏙! 자연물은 그대로 두었어요.');});
 }
 else if(q.id==='bus'||(q.id==='road'&&second)){
  const bus=q.id==='bus';m.pos??=40;m.arrived??=0;m.trail??=[40];const targets=bus?(second?[7,24,15,32,6,47]:[6,31,8,39,0,47]):[7,24,15,32,6,47];const blocked=bus?[10,11,18,19,34,35]:[10,11,12,26,27,34,35];const names=bus?['🏫 학교','🏥 병원','🛍️ 시장','🏠 마을','🌳 공원','🏁 차고']:['🏫 학교','🏠 집','🏫 학교','🏠 집','🏫 학교','🏁 도착'];const target=targets[m.arrived]??47;m.round=Math.floor(m.arrived/2);const nearby=Array.from({length:48},(_,i)=>i).filter(i=>adjacent(m.pos,i)&&!blocked.includes(i));
  const body=`<div class="travel-grid scene-bg" role="group" aria-label="${bus?'버스':'안전한 인도'} 이동판">${Array.from({length:48},(_,i)=>button(i===m.pos?(bus?art(7):'🚶'):blocked.includes(i)?'🚧':i===target?names[m.arrived]:(m.trail.includes(i)?'·':''),`data-cell="${i}" aria-label="${Math.floor(i/8)+1}행 ${i%8+1}열 ${i===m.pos?'현재 위치':i===target?'목표 '+names[m.arrived]:blocked.includes(i)?'공사 중':'길'}" ${blocked.includes(i)?'disabled':''}`,'travel-cell '+(i===m.pos?'vehicle ':i===target?'destination ':'')+(nearby.includes(i)?'reachable':''))).join('')}</div><div class="travel-tools"><b>${m.arrived} / 6 도착</b><span>다음: ${names[m.arrived]||'모두 도착!'}</span>${button('💡 가까운 길 보기','id="routeHint"','quiet')}</div>`;
  draw(bus?(second?'시장까지 이어지는 마을 버스':'주민을 태우고 출발!'):'공사를 피해 학교까지!',body,'반짝이는 옆 칸을 눌러요. 방향키로도 이동!');
  const takeStep=n=>{if(!nearby.includes(n))return again('지금 있는 곳의 바로 옆, 반짝이는 길을 눌러요.');m.pos=n;m.trail.push(n);if(n===target){m.arrived++;m.round=Math.floor(m.arrived/2);chime();again('도착! 다음 이웃을 만나러 가요.');}else again('좋아요! 공사 구역은 피해 가요.');};bind('[data-cell]',el=>takeStep(+el.dataset.cell));document.onkeydown=e=>{const delta={ArrowUp:-8,ArrowDown:8,ArrowLeft:-1,ArrowRight:1}[e.key];if(delta===undefined||$('resetDialog').open||e.ctrlKey||e.metaKey||e.altKey)return;e.preventDefault();const n=m.pos+delta;if(n>=0&&n<48&&nearby.includes(n)){takeStep(n);document.querySelector('.vehicle')?.focus({preventScroll:true});}};if($('routeHint'))$('routeHint').onclick=()=>{const queue=[[m.pos]],seen=new Set([m.pos]);while(queue.length){const path=queue.shift(),n=path.at(-1);if(n===target){document.querySelector(`[data-cell="${path[1]??n}"]`)?.classList.add('route-hint');notice('노란 칸으로 한 걸음!');break;}for(let i=0;i<48;i++)if(adjacent(n,i)&&!blocked.includes(i)&&!seen.has(i)){seen.add(i);queue.push([...path,i]);}}};
 }
 else if(q.id==='clinic'){
  m.served??=0;m.pack??=[];m.selected??=null;const people=[{icon:'🚨',name:'위급한 주민',items:[0,1],dest:0},{icon:'🩺',name:'정기 진료 주민',items:[2,3],dest:1},{icon:'🔬',name:'검사할 주민',items:[3,4],dest:2}];const p=people[(m.served+(second?0:1))%3];const supplies=['📞 연락','🧑‍⚕️ 의료진','📅 예약','📋 진료 기록','🚌 이동'];const destinations=['🚨 119·의료진','🩺 가까운 진료','🔬 검사 병원'];m.round=Math.floor(m.served/2);
  const body=`<div class="dispatch-stage scene-bg"><div class="resident-card">${art(m.served%2?4:2)}<b>${p.icon} ${p.name}</b><span>챙길 것: ${p.items.map(i=>supplies[i]).join(' + ')}</span><div class="pack-slots">${p.items.map(i=>`<span>${m.pack.includes(i)?supplies[i]:'＋'}</span>`).join('')}</div></div></div><div class="supply-row">${supplies.map((s,i)=>button(s,`data-supply="${i}" ${m.pack.includes(i)?'disabled':''}`)).join('')}</div><div class="dispatch-row">${destinations.map((d,i)=>button(d,`data-send="${i}" ${m.pack.length<2?'disabled':''}`)).join('')}</div><p class="counter">${m.served} / 6 주민 연결</p>`;
  draw(second?'급한 주민부터 도움 연결!':'주민 도움 꾸러미',body,'필요한 물품 두 개 → 도움받을 곳으로 보내요.');
  bind('[data-supply]',el=>{const i=+el.dataset.supply;if(!p.items.includes(i))return again('주민 카드에 있는 물품을 챙겨요.');m.pack.push(i);again('꾸러미에 담았어요!');});bind('[data-send]',el=>{if(+el.dataset.send!==p.dest)return again('주민 카드와 같은 그림의 도움받을 곳을 골라요.');m.served++;m.pack=[];m.round=Math.floor(m.served/2);chime();again('연결 완료! 다음 주민을 도와요.');});
 }
 else if(q.id==='house'){
  m.cleaned??=[];m.placed??=[];m.decor??={};m.tool??=0;const roomTools=[['📚 책장','🪑 의자','🎨 그림'],['🛏️ 침대','🪴 화분','💡 등'],['🪑 의자','☕ 탁자','🌿 화분']];const tools=second?['🪴 화분','🪑 의자','🌙 조용한 등']:roomTools[Math.min(m.round,2)];const positions=[[17,17],[53,18],[77,24],[28,62],[61,65]];const dirt=['🕸️','🍂','📦','🕸️','🍂'];const stage=m.cleaned.length<5?'clean':'decorate';
  const body=`<div class="restore-stage scene-bg"><span class="room-name">${['모임 방','가족의 집','이웃 쉼터'][m.round]||'완료'}</span>${stage==='clean'?positions.map(([x,y],i)=>button(dirt[(i+m.round)%5],`data-clean="${i}" style="left:${x}%;top:${y}%" ${m.cleaned.includes(i)?'disabled':''}`,'restore-spot '+(m.cleaned.includes(i)?'collected':''))).join(''):[22,49,76].map((x,i)=>button(m.placed.includes(i)?tools[m.decor[i]]:'＋',`data-place="${i}" style="left:${x}%;top:48%" ${m.placed.includes(i)?'disabled':''}`,'furniture-spot')).join('')}</div><div class="supply-row">${stage==='clean'?`<b>🧹 거미줄·낙엽·상자 ${m.cleaned.length} / 5 정리</b>`:tools.map((t,i)=>button(t,`data-tool="${i}" aria-pressed="${m.tool===i}"`,'')).join('')}</div>`;
  draw(second?'이웃을 위한 집 꾸미기':'빈집에 새 생명을!',body,stage==='clean'?'어질러진 곳을 눌러 깨끗하게 정리해요.':'마음에 드는 가구를 고르고 ＋ 자리에 놓아요.');
  bind('[data-clean]',el=>{m.cleaned.push(+el.dataset.clean);again(m.cleaned.length===5?'깨끗해졌어! 이제 가구를 놓아 볼까?':'쓱싹! 새 집에 한 걸음!');});bind('[data-tool]',el=>{m.tool=+el.dataset.tool;again(`${tools[m.tool]} 놓을 자리를 골라요.`);});bind('[data-place]',el=>{const i=+el.dataset.place;m.decor[i]=m.tool;m.placed.push(i);if(m.placed.length===3){finishRound();m.cleaned=[];m.placed=[];m.decor={};m.tool=0;}again('멋진 자리야!');});
 }
 else if(q.id==='road'){
  m.turns??=Array.from({length:16},(_,i)=>(i+m.round)%3+1);m.tested??=false;const level=PIPE_LEVELS[Math.min(m.round,2)],flow=waterPath(level,m.turns);const symbols=['╵','╶','╷','╴'];
  const body=`<div class="water-labels"><b>💧 왼쪽 위 입구 →</b><span>누르면 시계 방향으로 회전 ↻</span><b>↘ 🏠 오른쪽 아래 출구</b></div><div class="water-grid scene-bg">${Array.from({length:16},(_,i)=>{const ports=pipePorts(level.path,i).map(d=>(d+m.turns[i])%4);return button(`<span class="pipe-drawing">${ports.map(d=>`<i class="port port-${d}"></i>`).join('')}<i class="joint"></i></span>`,`data-turn="${i}" aria-label="${Math.floor(i/4)+1}행 ${i%4+1}열 관 돌리기"`,'water-cell '+(m.tested&&flow.wet.includes(i)?'wet ':'')+(i===0?'inlet ':i===15?'outlet':''));}).join('')}</div><div class="travel-tools">${button('💧 물 흘려 보기','id="testWater"','primary')}${button('💡 다음 관 힌트','id="pipeHint"','quiet')}</div>`;
  draw('빙글빙글 물길 수리!',body,'입구에서 출구까지 관을 이어 물을 보내요.');bind('[data-turn]',el=>{const i=+el.dataset.turn;m.turns[i]=(m.turns[i]+1)%4;m.tested=false;again('빙글! 물길을 이어 봐요.');});if($('testWater'))$('testWater').onclick=()=>{m.tested=true;if(flow.done){finishRound();m.turns=Array.from({length:16},(_,i)=>(i+m.round)%3+1);m.tested=false;again('💧 물이 도착했어! 다음 구역도 고쳐 보자.');}else again('파란 관까지 물이 왔어요. 끊긴 곳을 고쳐요.');};if($('pipeHint'))$('pipeHint').onclick=()=>{const i=level.path.find(n=>m.turns[n]%4!==0&&!(pipePorts(level.path,n).every(d=>pipePorts(level.path,n).includes((d+m.turns[n])%4))));if(i!==undefined){document.querySelector(`[data-turn="${i}"]`)?.classList.add('route-hint');notice('노란 관을 돌려 봐요. 입구는 왼쪽!');}};
 }
 save();
}
