'use strict';
const STORE='wando_town_hero_v3';
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shuffle=n=>Array.from({length:n},(_,i)=>i).sort(()=>Math.random()-.5);
const fresh=()=>({version:3,active:null,quests:{},completed:{}});
let state,saveError=false;try{state=JSON.parse(localStorage.getItem(STORE));if(!state||state.version!==3||!state.quests||!state.completed)state=fresh();}catch{state=fresh();saveError=true;}
document.body.innerHTML=`<header><a href="#" id="home" aria-label="마을 지도로">🏝️ <span>완도ON 2<small>우리 마을 해결사</small></span></a><nav><button id="music" aria-pressed="false">♫ 음악 켜기</button><button id="reset">다시 시작</button></nav></header><main id="app"></main><p id="save" role="status">자동 저장</p><div id="toast" role="status" aria-live="polite"></div><dialog id="resetDialog" aria-labelledby="resetTitle"><h2 id="resetTitle"></h2><p id="resetText"></p><div class="actions"><button id="cancelReset">취소</button><button id="confirmReset" class="primary">다음 확인</button></div></dialog><audio id="bgm" src="assets/peaceful-village.ogg" loop preload="none"></audio>`;
const bgm=$('bgm');bgm.volume=.22;let musicOn=false,audioContext,toastTimer;
function save(){try{localStorage.setItem(STORE,JSON.stringify(state));saveError=false;}catch{saveError=true;}$('save').textContent=saveError?'이 기기에서 저장이 안 돼요. 창을 닫기 전에 확인해 주세요.':'✓ 자동 저장';}
function notice(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2600);}
function chime(){if(!musicOn)return;try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();const t=audioContext.currentTime;[523,659,784].forEach((f,i)=>{const o=audioContext.createOscillator(),g=audioContext.createGain();o.frequency.value=f;o.connect(g);g.connect(audioContext.destination);g.gain.setValueAtTime(.035,t+i*.07);g.gain.exponentialRampToValueAtTime(.001,t+i*.07+.2);o.start(t+i*.07);o.stop(t+i*.07+.22);});}catch{}}
async function toggleMusic(){if(musicOn){musicOn=false;bgm.pause();}else{try{await bgm.play();musicOn=true;}catch{notice('음악을 재생하지 못했어요. 다시 눌러 주세요.');musicOn=false;}}$('music').textContent=musicOn?'♫ 음악 끄기':'♫ 음악 켜기';$('music').setAttribute('aria-pressed',String(musicOn));}
document.addEventListener('visibilitychange',()=>{if(document.hidden)bgm.pause();else if(musicOn)bgm.play().catch(()=>{musicOn=false;$('music').textContent='♫ 음악 켜기';$('music').setAttribute('aria-pressed','false');});});
bgm.addEventListener('error',()=>{musicOn=false;$('music').textContent='♫ 음악 켜기';$('music').setAttribute('aria-pressed','false');notice('음악 파일을 불러오지 못했어요. 게임은 계속할 수 있어요.');});
function art(n,cls=''){return `<span class="art ${cls}" style="--x:${n%3*50}%;--y:${Math.floor(n/3)*50}%" aria-hidden="true"></span>`;}
function button(text,attrs='',cls=''){return `<button ${attrs} class="${cls}">${text}</button>`;}
function bind(selector,fn){document.querySelectorAll(selector).forEach(el=>el.onclick=()=>fn(el));}
function totals(){return [0,1,2,3].map(i=>Object.values(state.completed).reduce((sum,r)=>sum+r.score[i],0));}
function record(){return {phase:0,page:0,mini:{},second:{},first:null,final:null,value:null,clue:false,errors:0,order:shuffle(3),evidenceOrder:shuffle(3),finalOrder:shuffle(3)};}
function current(){return CASES.find(q=>q.id===state.active);}
function entry(){return state.quests[state.active];}
function move(phase){entry().phase=phase;entry().page=0;save();render();$('phaseHeading')?.focus();}
function goMap(){state.active=null;save();renderMap();}
function open(id){state.active=id;state.quests[id]??=record();save();render();}
function dialogue(person,text){const p=PEOPLE[person];return `<div class="dialogue"><div class="portrait">${art(p[2])}</div><div class="speech"><span class="speaker">${esc(p[0])} <small>${esc(p[1])}</small></span><p>${esc(text)}</p></div></div>`;}
function frame(title,inside,actions=''){const q=current(),r=entry();$('app').innerHTML=`<div class="casebar">${button('← 마을','id="back"','quiet')}<span>${q.icon} ${q.name}</span><span class="steps">${['이야기','찾기','단서','계획','새 소식','돕기','다시 선택','돌아보기','완료'][r.phase]}</span></div><section class="case-shell ${q.id}"><div class="case-title"><span>의뢰 ${CASES.indexOf(q)+1}</span><h2 id="phaseHeading" tabindex="-1">${esc(title)}</h2></div>${inside}<div class="actions">${actions}</div></section>`;$('back').onclick=goMap;}
function renderMap(){const done=Object.keys(state.completed).length;const scores=totals();$('app').innerHTML=`<section class="welcome"><div><span class="eyebrow">작은 탐정, 큰 도움!</span><h1>오늘은 어디로 갈까?</h1><p>그림을 누르고, 단서를 찾아 이웃을 도와줘요.</p></div>${art(0,'guide')}</section><div class="map"><div class="sea-water"></div><div class="island"></div><div class="map-road"></div><div class="trees">🌳 🌳 🌲</div>${CASES.map((q,i)=>`<button class="map-node node-${i} ${state.completed[q.id]?'done':''}" data-quest="${q.id}">${i===0?art(6):i===1?art(7):i===3?art(8):`<span class="building">${q.icon}</span>`}<b>${q.name}</b><small>${state.completed[q.id]?'✓ 해결 완료':state.quests[q.id]?'이어서 하기':'도움 요청!'}</small></button>`).join('')}<span class="map-boat">⛵</span><span class="map-cloud">☁️</span></div><section class="progress"><b>🏅 ${done} / 5 해결</b><div class="badge-dots">${CASES.map(q=>`<span class="${state.completed[q.id]?'earned':''}" title="${q.badge}">${q.icon}</span>`).join('')}</div>${button('🏆 해결사 평가서',`id="resultGate" ${done<5?'disabled':''}`,'primary')}</section><details class="grownups"><summary>선생님·보호자 / 그림과 음악</summary><p>초4 사회: 여러 해결방법의 좋은 점과 아쉬운 점을 비교해요. 시간 제한과 게임오버 없이 다시 도전할 수 있어요.</p><p>네 관점: ${VALUES.map((v,i)=>`${v} ${scores[i]}`).join(' · ')}</p><p>그림: 이 게임을 위해 AI로 제작. 음악: Bobjt의 <a href="https://opengameart.org/content/peacefull-ville" target="_blank" rel="noopener">peacefull ville (CC0)</a>.</p><p>이전 버전의 기록은 따로 보존됩니다.</p></details>`;bind('[data-quest]',el=>open(el.dataset.quest));$('resultGate').onclick=result;}
function render(){if(!current())return goMap();const q=current(),r=entry();if(r.phase===0){const [p,t]=q.talk[r.page];frame(q.title,dialogue(p,t),button(r.page===2?'🔎 현장으로!':'이야기 계속 ▸','id="next"','primary'));$('next').onclick=()=>{if(r.page<2){r.page++;save();render();}else move(1);};}
 else if(r.phase===1||r.phase===5)mini();
 else if(r.phase===2)clue();
 else if(r.phase===3)plans(false);
 else if(r.phase===4){const pages=[[q.person,q.outcomes[r.first]],...q.follow];const [p,t]=pages[r.page];frame(r.page===0?'내 계획의 결과':'새로운 부탁!',dialogue(p,t),button(r.page===2?'🎮 한 번 더 도와주기':'다음 이야기 ▸','id="next"','primary'));$('next').onclick=()=>{if(r.page<2){r.page++;save();render();}else move(5);};}
 else if(r.phase===6)plans(true);
 else if(r.phase===7){frame('내가 챙긴 것은?',dialogue(0,'오늘 가장 마음에 남는 도움은 뭐야?')+`<div class="value-grid">${VALUES.map((v,i)=>button(v,`data-value="${i}"`)).join('')}</div>`);bind('[data-value]',el=>{r.value=+el.dataset.value;finish();});}
 else completion();}
function clue(){const q=current(),r=entry();frame('잠깐! 단서를 보여줘요',dialogue(q.person,q.claim)+`<div class="clue-tray"><span class="tray-label">내 단서 가방</span><div class="choice-grid">${r.evidenceOrder.map(i=>button(`<span class="big-icon">${q.evidence[i][0]}</span><b>${q.evidence[i][1]}</b>`,`data-evidence="${i}"`,'evidence')).join('')}</div></div>`);bind('[data-evidence]',el=>{if(+el.dataset.evidence!==q.answer){r.errors++;save();notice('문제와 이어지는 단서를 골라 봐요.');el.classList.add('wrong');return;}r.clue=true;save();chime();frame('단서 발견!',`<div class="callout">단서 발견!</div>`+dialogue(0,q.explain),button('💡 해결방법 고르기','id="next"','primary'));$('next').onclick=()=>move(3);});}
function plans(second){const q=current(),r=entry(),list=second?q.solutions:q.plans,selected=second?r.final:r.first,order=second?r.finalOrder:r.order;frame(second?'어떻게 더 도울까?':'우리의 첫 계획은?',dialogue(0,second?'처음 방법을 더 좋게 바꿔도, 이어가도 좋아!':'좋은 점도, 아쉬운 점도 있어. 마음에 드는 방법은?')+`<div class="choice-grid plan-grid">${order.map(i=>button(`<span class="big-icon">${list[i][0]}</span><b>${list[i][1]}</b>${second?`<small>${list[i][2]}</small>`:`<small class="good">👍 ${list[i][2]}</small><small class="limit">🤔 ${list[i][3]}</small>`}`,`data-plan="${i}" aria-pressed="${selected===i}"`,'plan '+(selected===i?'selected':''))).join('')}</div>`,button(second?'이 방법으로 도와줄게!':'이 계획으로 출발!',`id="next" ${selected===null?'disabled':''}`,'primary'));bind('[data-plan]',el=>{if(second)r.final=+el.dataset.plan;else r.first=+el.dataset.plan;save();plans(second);});$('next').onclick=()=>move(second?7:4);}
function score(q,r){const a=q.plans[r.first][4],b=q.solutions[r.final][3];return a.map((v,i)=>Math.round(2*(v*.3+b[i]*.5+8*.2)));}
function finish(){const q=current(),r=entry();if(!state.completed[q.id])state.completed[q.id]={first:r.first,final:r.final,value:r.value,score:score(q,r),errors:r.errors};r.phase=8;save();chime();render();}
function completion(){const q=current(),r=state.completed[q.id];frame('의뢰 해결!',`<div class="celebrate"><span class="medal">${q.icon}</span><h3>${q.badge}</h3><p>${q.solutions[r.final][2]}</p><div class="badge-values">${VALUES.map((v,i)=>`<span>${v}<b>+${r.score[i]}</b></span>`).join('')}</div></div>`,button('🏝️ 마을로!','id="goMap"','primary')+button('다시 놀기','id="replay"','quiet'));$('goMap').onclick=goMap;$('replay').onclick=()=>{state.quests[q.id]=record();save();render();notice('다시 놀아도 점수는 한 번만 받아요.');};}
function rankFor(v){const avg=v.reduce((a,b)=>a+b,0)/4,min=Math.min(...v);return avg>=85&&min>=75?'S':avg>=75&&min>=60?'A':avg>=60&&min>=40?'B':'C';}
function result(){if(Object.keys(state.completed).length<5)return;const v=totals(),rank=rankFor(v),hi=v.indexOf(Math.max(...v)),lo=v.indexOf(Math.min(...v));$('app').innerHTML=`<section class="result-sheet"><span class="eyebrow">다섯 이웃을 도왔어!</span><h1>우리 마을 해결사</h1><span class="rank">${rank}</span><p>총점 ${v.reduce((a,b)=>a+b,0)} / 400</p><div class="score-bars">${VALUES.map((s,i)=>`<div><b>${s}</b><progress max="100" value="${v[i]}"></progress><span>${v[i]}</span></div>`).join('')}</div><p>잘한 관점: ${VALUES[hi]}<br>다음에 더 챙길 관점: ${VALUES[lo]}</p><div class="result-cases">${CASES.map(q=>{const r=state.completed[q.id];return `<details><summary>${q.icon} ${q.name} · ${q.solutions[r.final][1]}</summary><p>첫 계획: ${q.plans[r.first][1]}</p><p>👍 ${q.solutions[r.final][2]}</p><p>🤔 ${q.plans[r.first][3]}</p><p>내가 챙긴 것: ${VALUES[r.value]}</p></details>`;}).join('')}</div>${button('마을로 돌아가기','id="goMap"','primary')}</section>`;$('goMap').onclick=goMap;}
function feedback(m,text,success=false){m.message=text;if(success)chime();save();mini();}
function mini(){const q=current(),r=entry(),second=r.phase===5,m=second?r.second:r.mini;m.message??='';let content='';
 if(q.id==='sea'){m.picked??=[];const items=second?[['🧴','플라스틱병',true],['🪢','버려진 줄',true],['📦','상자',true],['🐚','조개',false],['🍃','해초',false],['🛍️','비닐봉지',true],['🦀','게',false],['🪨','돌',false]]:[['🧴','플라스틱병',true],['🐚','조개',false],['🛍️','비닐봉지',true],['🦀','게',false],['📦','상자',true],['🍃','해초',false],['🪢','버려진 줄',true],['🪨','돌',false]];m.done=m.picked.length===4;
 content=`<div class="mini-hint">${second?'쓰레기를 주운 뒤, 다시 오는 길을 골라요.':q.miniHint}</div><div class="beach board">${items.map((it,i)=>button(`${it[0]==='🧴'?art(6):`<span class="item-icon">${it[0]}</span>`}<small>${it[1]}</small>`,`data-item="${i}" ${m.picked.includes(i)?'disabled':''}`,'beach-item '+(m.picked.includes(i)?'collected':''))).join('')}</div><div class="counter">🧺 ${m.picked.length} / 4 주웠어요</div>`;
 if(second&&m.done){content+=`<div class="source-choices">${button('🏞️ 하천에서 내려옴','data-source="0"')}${button('🐚 조개가 만듦','data-source="1"')}</div>`;m.done=m.source===0;}
 frame(second?q.secondTitle:q.miniTitle,content+miniMessage(m),miniNext(m,second));bind('[data-item]',el=>{const i=+el.dataset.item;if(!items[i][2]){r.errors++;feedback(m,'그건 자연물! 그대로 두면 돼요.');}else{m.picked.push(i);feedback(m,'쏙! 하나 주웠어요.',true);}});bind('[data-source]',el=>{m.source=+el.dataset.source;feedback(m,m.source===0?'맞아요! 하천에서 오는 쓰레기도 줄여요.':'조개는 쓰레기를 만들지 않아요. 하천을 살펴봐요.',m.source===0);});}
 else if(q.id==='bus'){m.stops??=[];const names=['🏫 학교','🏥 병원','🛍️ 시장','🌳 공원'],needed=second?[0,1,2]:[0,1];m.done=needed.every(i=>m.stops.includes(i));content=`<div class="rider-strip">${art(2)}<span>🏥 병원</span>${art(4)}<span>🏫 학교</span>${second?'<span>🛍️ 시장 주민도!</span>':''}</div><div class="route-board board"><div class="route-bus">${art(7)}<span>출발!</span></div><div class="route-track ${m.stops.length?'connected':''}"></div><div class="route-stops">${names.map((n,i)=>button(n,`data-stop="${i}" aria-pressed="${m.stops.includes(i)}"`,'stop '+(m.stops.includes(i)?'selected':''))).join('')}</div></div><p class="mini-hint">${second?'학교·병원 길에 시장도 이어 주세요.':'학교와 병원 정류장을 눌러 이어요.'}</p>`;frame(second?q.secondTitle:q.miniTitle,content+miniMessage(m),miniNext(m,second));bind('[data-stop]',el=>{const i=+el.dataset.stop;if(m.stops.includes(i))m.stops=m.stops.filter(n=>n!==i);else m.stops.push(i);feedback(m,needed.includes(i)?'필요한 길이 이어졌어요!':'공원도 좋지만, 지금 갈 곳을 먼저 이어요.',needed.includes(i));});}
 else if(q.id==='clinic'){m.answers??=[];const n=m.answers.length;m.done=n===3;const patients=second?[['🚨','갑자기 위급해요','119·의료진',0],['🩺','정기 진료예요','가까운 진료',1],['🔬','큰 검사가 필요해요','검사 병원 연결',2]]:[['🩺','정기 진료를 받아요','가까운 진료',1],['🔬','큰 검사를 받아요','검사 병원 연결',2],['🚨','갑자기 위급해요','119·의료진',0]];const a=patients[Math.min(n,2)];content=m.done?`<div class="mini-cleared">${art(3)}<h3>세 주민 모두 연결!</h3><p>급한 도움은 119·의료진에게 먼저.</p></div>`:`<div class="patient board">${art(n===1?4:2)}<div><span class="big-icon">${a[0]}</span><h3>${a[1]}</h3><span class="hint-chip">필요한 도움: ${a[2]}</span></div></div><div class="choice-grid">${['🚨 119·의료진','🩺 가까운 진료','🔬 검사 병원 연결'].map((t,i)=>button(t,`data-help="${i}"`)).join('')}</div><p class="counter">${n} / 3 연결</p>`;frame(second?q.secondTitle:q.miniTitle,content+miniMessage(m),miniNext(m,second));bind('[data-help]',el=>{if(+el.dataset.help!==a[3]){r.errors++;feedback(m,'주민이 필요한 도움과 같은 버튼을 골라요.');}else{m.answers.push(a[3]);feedback(m,'도움 연결 완료!',true);}});}
 else if(q.id==='house'){m.answers??=[];const n=m.answers.length;m.done=n===3;const houses=second?[['학생들이 모일 집', '낮에 함께 쓰기',1],['이웃이 쉬는 저녁','조용한 시간',2],['입주할 가족이 있어요','살 집',0]]:[['입주할 가족이 있어요','살 집',0],['학교 앞, 놀 곳이 없어요','함께 쓰기',1],['벽이 무너질 것 같아요','안전 점검',2]];const a=houses[Math.min(n,2)],labels=second?['🏠 살 집','🎨 낮에 함께 쓰기','🌙 조용한 시간']:['🏠 살 집','🎨 함께 쓰기','🛠️ 안전 점검'];content=m.done?`<div class="mini-cleared">${art(8)}<h3>마을에 새 역할이 생겼어!</h3></div>`:`<div class="house-card board">${art(8)}<h3>${a[0]}</h3><span class="hint-chip">${a[1]}부터 생각해 봐요</span></div><div class="choice-grid">${labels.map((t,i)=>button(t,`data-use="${i}"`)).join('')}</div><p class="counter">${n} / 3 도움</p>`;frame(second?q.secondTitle:q.miniTitle,content+miniMessage(m),miniNext(m,second));bind('[data-use]',el=>{if(+el.dataset.use!==a[2]){r.errors++;feedback(m,'집의 작은 힌트를 한 번 더 봐요.');}else{m.answers.push(a[2]);feedback(m,'딱 맞는 도움을 찾았어요!',true);}});}
 else if(q.id==='road'){if(!second){m.turns??=[0,1,0,1];m.done=m.turns.every(n=>n===1);content=`<p class="mini-hint">가로 관 ━ 네 개를 이어 주세요.</p><div class="pipe-board board"><span class="water-start">💧</span>${m.turns.map((n,i)=>button(`<span class="pipe ${n?'horizontal':''}"></span>`, `data-pipe="${i}" aria-label="${i+1}번 관 ${n?'가로':'세로'} 돌리기"`,'pipe-cell')).join('')}<span class="water-end">🏠</span></div><p class="counter">${m.done?'💧 물길이 이어졌어요!':'관을 누르면 빙글! 돌아가요.'}</p>`;frame(q.miniTitle,content+miniMessage(m),miniNext(m,second));bind('[data-pipe]',el=>{const i=+el.dataset.pipe;m.turns[i]=1-m.turns[i];feedback(m,'관 조각을 돌렸어요.',m.turns.every(n=>n===1));});}else{m.path??=[];const tiles=[['🚧','공사 중',false],['🌳','인도',true],['🚗','차도',false],['🌳','인도',true],['💧','새는 곳',false],['🏫','학교',true]];m.done=[1,3,5].every(i=>m.path.includes(i));content=`<p class="mini-hint">인도 두 곳 → 학교 순서로 눌러요.</p><div class="safe-path board"><div class="walker">${art(4)}</div>${tiles.map((t,i)=>button(`<span>${t[0]}</span><small>${t[1]}</small>`,`data-path="${i}" ${m.path.includes(i)?'disabled':''}`,'path-tile '+(m.path.includes(i)?'selected':''))).join('')}</div><p class="counter">${m.path.length} / 3 안전한 길</p>`;frame(q.secondTitle,content+miniMessage(m),miniNext(m,second));bind('[data-path]',el=>{const i=+el.dataset.path,expected=[1,3,5][m.path.length];if(i!==expected){r.errors++;feedback(m,tiles[i][2]?'가까운 인도부터 이어 가요.':'위험한 곳! 나무가 있는 인도로 가요.');}else{m.path.push(i);feedback(m,i===5?'학교 도착! 원인 보수도 계속해요.':'안전한 인도로 한 걸음!',true);}});}}
 if($('next'))$('next').onclick=()=>{if(!m.done)return;move(second?6:2);};save();}
function miniMessage(m){return `<p class="mini-message" role="status">${esc(m.message||'잘못 눌러도 괜찮아요. 다시 해 봐요!')}</p>`;}
function miniNext(m,second){return button(second?'💡 마지막 방법 고르기':'🎒 단서 가방에 넣기',`id="next" ${m.done?'':'disabled'}`,'primary');}
let resetStep=1;function resetDialog(step){resetStep=step;$('resetTitle').textContent=step===1?'처음부터 시작할까요?':'정말 새 게임 기록을 지울까요?';$('resetText').textContent=step===1?'진행 중인 새 게임 기록이 초기화돼요.':'확인하면 점수와 배지도 지워져요. 이전 버전 기록은 남아요.';$('confirmReset').textContent=step===1?'다음 확인':'기록 지우고 새로 시작';if(!$('resetDialog').open)$('resetDialog').showModal();$('cancelReset').focus();}
$('reset').onclick=()=>resetDialog(1);$('cancelReset').onclick=()=>$('resetDialog').close();$('confirmReset').onclick=()=>{if(resetStep===1)return resetDialog(2);state=fresh();save();$('resetDialog').close();renderMap();};$('home').onclick=e=>{e.preventDefault();goMap();};$('music').onclick=toggleMusic;
save();if(state.active&&CASES.some(q=>q.id===state.active))render();else renderMap();