function responseBoard(){const q=currentQuest,r=qstate(),l=LESSONS[q.id],n=r.event,d=r.decisions[n];d.board||={routes:[...r.routes[n]],order:[],houses:[],targets:[]};const b=d.board;let body=`<span class="pill">실행 계획 ${n+1}/3</span><h3>${esc(taskFor(q,r,n).actions[d.action][0])}</h3><p>${esc(taskFor(q,r,n).detail)}</p>`,ready=false;
 if(q.id==='sea'){const amounts=[[7,2,3],[3,6,3],[8,3,2]][n];body+=`<h4>추가 활동을 먼저 할 장소 두 곳을 정해요</h4><p>조사량과 주민의 활동 시간을 함께 보세요. 두 곳까지만 먼저 방문할 수 있어요.</p><div class="route-board">${l.groups.map((g,i)=>button(`${g}: 쓰레기 ${amounts[i]}개 관찰`, `data-target="${i}"`,b.targets.includes(i)?'route-place selected':'route-place')).join('')}</div><p>내 방문: ${b.targets.map(i=>esc(l.groups[i])).join(' → ')||'미선택'}</p>`;ready=b.targets.length===2;
 }else if(q.id==='bus'){body+=`<h4>${esc(l.rounds[n][0])} 실제 노선 조정</h4><p>두 목적지를 연결하세요. 기존 노선을 유지해도 됩니다. 빠지는 주민에게는 선택한 대응 방법을 함께 적용해요.</p><div class="route-board">${l.rounds[n][2].map((g,i)=>button(g,`data-revise-route="${i}"`,b.routes.includes(i)?'route-place selected':'route-place')).join('')}</div><p>빠진 목적지: ${l.rounds[n][2].filter((_,i)=>!b.routes.includes(i)).map(esc).join(' / ')}</p><h4>빠진 목적지에 적용할 보완은?</h4>${choices(['다른 시간대 연결·환승 안내','이동할 필요가 없다고 가정','다른 교통 지원 가능 여부 확인'],'data-route-backup',b.backup)}`;ready=b.routes.length===2&&b.backup!=null;
 }else if(q.id==='clinic'){const patients=[['응급 도움 요청: 119·의료진 즉시 연결','예정된 일반 진료','예약된 전문 검사'],['응급 연결을 유지해야 하는 주민','먼 전문 검사 예약 주민','마을 기본 진료 예약 주민'],['갑작스러운 위급 도움 요청','거동 불편 예약 주민','가까운 일반 진료 예약 주민']][n];body+=`<h4>지원 연결 순서를 정해요</h4><p>직접 진단하는 활동은 아니에요. 응급 도움 연결 뒤 예약 주민의 치료 종류와 이동 부담을 비교해요.</p>${patients.map((p,i)=>button(p,`data-triage="${i}" ${b.order.includes(i)?'disabled':''}`)).join(' ')}<p>내 연결 순서: ${b.order.map(i=>esc(patients[i])).join(' → ')||'미선택'}</p>${button('연결 순서 다시 구성','id="clearTriage"')}<p class="hint">${b.order.length&&b.order[0]!==0?'응급 도움 연결을 먼저 확보하고 일반 예약에 변경을 안내해 보세요.':'예약 주민에게 변경된 순서도 알려 주세요.'}</p>`;ready=b.order.length===3;
 }else if(q.id==='house'){const houses=[['학교 앞 안전한 집 · 밤 소음 민원','입주 희망 가족이 있는 집','재사용이 어려운 위험한 집'],['이용자가 없는 카페','입주 희망 가족이 있는 집','관리자가 없는 공동 공간'],['안전 점검 통과한 집 · 학생 공간 수요','재사용 불가 판정 집','수리 가능하고 입주 가족이 있는 집']][n],uses=['주거 활용','공동 공간·시간 조정','안전 점검·철거 검토','운영 담당·수요 협의'];body+=`<h4>한 방법을 모든 집에 적용하지 않아도 돼요</h4><div class="field-cards">${houses.map((h,i)=>`<section class="field-card"><h4>${esc(h)}</h4>${choices(uses,`data-rehouse-${i}`,b.houses[i])}</section>`).join('')}</div>`;ready=[0,1,2].every(i=>b.houses[i]!=null);
 }else{const sites=[['A길: 지금 구멍 있음 · 보행자 접근','B길: 물이 반복해서 나옴 · 노후 관','C길: 점검 기록 정상'],['A길: 공사 중 · 통학로 막힘','B길: 틈이 넓어짐 · 관 누수 의심','C길: 평평함 · 최근 점검 정상'],['A길: 반복 누수 이력 · 오래된 관','B길: 새로 설치한 관 · 정상 기록','C길: 작은 침하 신호 발견']][n];body+=`<h4>두 지점을 먼저 관리해요</h4><p>사고 후 복구와 사고 전 예방을 비교해 순서를 정하세요. 위험 지점에는 직접 접근하지 않아요.</p><div class="route-board">${sites.map((p,i)=>button(p,`data-target="${i}"`,b.targets.includes(i)?'route-place selected':'route-place')).join('')}</div><p>내 관리 순서: ${b.targets.map(i=>esc(sites[i])).join(' → ')||'미선택'}</p>`;ready=b.targets.length===2;}
 body+=button('이 실행 계획의 결과 확인',`id="executeBoard" ${ready?'':'disabled'}`,'primary');shell(body);const update=()=>{save();responseBoard();};
 bind('[data-target]',button=>{const i=+button.dataset.target;if(b.targets.includes(i))b.targets.splice(b.targets.indexOf(i),1);else if(b.targets.length<2)b.targets.push(i);else toast('먼저 한 곳을 해제하고 다시 정해요.');update();});bind('[data-revise-route]',button=>{const i=+button.dataset.reviseRoute;if(b.routes.includes(i))b.routes.splice(b.routes.indexOf(i),1);else if(b.routes.length<2)b.routes.push(i);else toast('두 목적지만 연결할 수 있어요.');update();});bind('[data-route-backup]',button=>{b.backup=+button.dataset.routeBackup;update();});bind('[data-triage]',button=>{b.order.push(+button.dataset.triage);update();});if($('clearTriage'))$('clearTriage').onclick=()=>{b.order=[];update();};for(let i=0;i<3;i++)bind(`[data-rehouse-${i}]`,button=>{b.houses[i]=+button.getAttribute(`data-rehouse-${i}`);update();});$('executeBoard').onclick=()=>{d.boardFeedback=boardFeedback(q.id,n,b);d.stage=2;save();eventView();};
}
function boardFeedback(id,n,b){if(id==='sea')return b.targets.includes(n===1?1:0)?'조사에서 쓰레기가 많이 관찰된 장소를 포함했어요. 나머지 장소의 재발도 계속 확인해요.':'쓰레기가 많이 관찰된 장소가 빠졌어요. 다음 활동에서 그 장소도 확인할 필요가 있어요.';if(id==='bus')return b.backup===1?'빠진 목적지 주민의 이동 필요를 놓쳤어요. 다른 시간과 교통수단을 확인해요.':'빠진 목적지를 기록하고 다른 시간·교통으로 보완했어요. 기존 노선 유지도 근거가 있으면 가능합니다.';if(id==='clinic')return b.order[0]===0?'응급 연결을 먼저 확보했어요. 예약 주민에게는 필요한 기관과 변경 시간을 안내해요.':'일반 예약을 먼저 두어 응급 도움 연결이 늦어졌어요. 119·의료진 연결을 먼저 확보해요.';if(id==='house')return new Set(b.houses).size>1?'집마다 조건을 나누어 조정했어요. 안전과 실제 수요에 맞는지 계속 확인해요.':'모든 집에 같은 방법을 적용했어요. 안전 상태와 이용 수요가 다른 집을 다시 살펴요.';return b.targets.includes(n===2?2:1)&&b.targets.includes(0)?'현재 안전과 새 위험 신호가 있는 지점을 함께 살폈어요. 기록이 정상인 곳도 정기 확인해요.':'지금 위험하거나 새 신호가 있는 지점 일부가 빠졌어요. 겉면 복구와 예방 점검을 함께 비교해요.';}
function boardScore(id,n,b){if(!b)return 7;if(id==='clinic')return b.order[0]===0?10:4;if(id==='house'){const expected=[[1,0,2],[3,0,3],[1,2,0]][n];return 5+b.houses.filter((v,i)=>v===expected[i]).length*5/3;}if(id==='bus')return b.backup===1?4:9;if(id==='sea')return b.targets.includes(n===1?1:0)?9:6;return b.targets.includes(0)&&b.targets.includes(n===2?2:1)?10:5;}

